import type { ColorTokens } from "@/types";

function withChrome(
  base: Omit<
    ColorTokens,
    | "headerBackground"
    | "headerForeground"
    | "footerBackground"
    | "footerForeground"
    | "buttonBackground"
    | "buttonForeground"
  >,
  buttonForeground: string,
): ColorTokens {
  return {
    ...base,
    headerBackground: base.surface,
    headerForeground: base.foreground,
    footerBackground: base.surface,
    footerForeground: base.muted,
    buttonBackground: base.primary,
    buttonForeground,
  };
}

export type ThemeColorPackCategory =
  | "Nature"
  | "Warm"
  | "Modern"
  | "Luxury"
  | "Soft"
  | "Bold"
  | "Neutral"
  | "Dark";

export type ThemeColorPack = {
  id: string;
  name: string;
  description: string;
  category: ThemeColorPackCategory;
  /** Swatches: primary, secondary, accent, background */
  preview: [string, string, string, string];
  light: ColorTokens;
  dark: ColorTokens;
};

function pack(
  id: string,
  name: string,
  description: string,
  category: ThemeColorPackCategory,
  lightBase: Parameters<typeof withChrome>[0],
  lightBtnFg: string,
  darkBase: Parameters<typeof withChrome>[0],
  darkBtnFg: string,
): ThemeColorPack {
  const light = withChrome(lightBase, lightBtnFg);
  const dark = withChrome(darkBase, darkBtnFg);
  return {
    id,
    name,
    description,
    category,
    preview: [light.primary, light.secondary, light.accent, light.background],
    light,
    dark,
  };
}

/**
 * Curated look packs for merchants who are not designers.
 * Theme Editor consumes this library — components must not hardcode these hex values.
 */
export const THEME_COLOR_PACKS: ThemeColorPack[] = [
  pack(
    "forest",
    "Forest green",
    "Fresh and natural — groceries, wellness, organics.",
    "Nature",
    {
      primary: "#1a5f4a",
      secondary: "#2c3e50",
      accent: "#c4783a",
      background: "#f7f5f2",
      foreground: "#1a1a1a",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#e2ddd6",
      muted: "#6b6560",
      success: "#2e7d4f",
      warning: "#b7791f",
      error: "#b42318",
    },
    "#ffffff",
    {
      primary: "#4fd1a5",
      secondary: "#94a3b8",
      accent: "#e8a05c",
      background: "#0f1412",
      foreground: "#f2f0eb",
      surface: "#1a211e",
      card: "#222a26",
      border: "#2f3a35",
      muted: "#9ca89f",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#0f1412",
  ),
  pack(
    "ocean",
    "Ocean blue",
    "Calm and trustworthy — everyday retail and services.",
    "Modern",
    {
      primary: "#1d4e89",
      secondary: "#334155",
      accent: "#0ea5a0",
      background: "#f4f7fb",
      foreground: "#0f172a",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#d7e0ea",
      muted: "#64748b",
      success: "#15803d",
      warning: "#b45309",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#60a5fa",
      secondary: "#94a3b8",
      accent: "#2dd4bf",
      background: "#0b1220",
      foreground: "#e8eef7",
      surface: "#121a2a",
      card: "#182235",
      border: "#2a374d",
      muted: "#94a3b8",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#0b1220",
  ),
  pack(
    "spice",
    "Warm spice",
    "Rich and inviting — spices, kitchens, and food brands.",
    "Warm",
    {
      primary: "#9f1239",
      secondary: "#44403c",
      accent: "#d97706",
      background: "#fff8f0",
      foreground: "#1c1917",
      surface: "#fffdf9",
      card: "#ffffff",
      border: "#eadfce",
      muted: "#78716c",
      success: "#3f6212",
      warning: "#a16207",
      error: "#b91c1c",
    },
    "#fff8f0",
    {
      primary: "#fb923c",
      secondary: "#a8a29e",
      accent: "#fbbf24",
      background: "#140f0c",
      foreground: "#faf6f1",
      surface: "#1f1712",
      card: "#2a1f18",
      border: "#3f2e24",
      muted: "#a8a29e",
      success: "#a3e635",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#140f0c",
  ),
  pack(
    "ink",
    "Modern ink",
    "Clean black and white — premium and simple.",
    "Neutral",
    {
      primary: "#111827",
      secondary: "#4b5563",
      accent: "#2563eb",
      background: "#f8fafc",
      foreground: "#0f172a",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#e2e8f0",
      muted: "#64748b",
      success: "#15803d",
      warning: "#b45309",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#f8fafc",
      secondary: "#94a3b8",
      accent: "#60a5fa",
      background: "#020617",
      foreground: "#f8fafc",
      surface: "#0f172a",
      card: "#111827",
      border: "#1e293b",
      muted: "#94a3b8",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#020617",
  ),
  pack(
    "blush",
    "Soft blush",
    "Gentle and stylish — beauty and lifestyle.",
    "Soft",
    {
      primary: "#9d174d",
      secondary: "#57534e",
      accent: "#db2777",
      background: "#fdf8f9",
      foreground: "#1c1917",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#eadde2",
      muted: "#78716c",
      success: "#15803d",
      warning: "#b45309",
      error: "#be123c",
    },
    "#ffffff",
    {
      primary: "#f472b6",
      secondary: "#a8a29e",
      accent: "#fb7185",
      background: "#1a1014",
      foreground: "#fdf8f9",
      surface: "#26151c",
      card: "#301b24",
      border: "#4a2a36",
      muted: "#a8a29e",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#fb7185",
    },
    "#1a1014",
  ),
  pack(
    "slate",
    "Cool slate",
    "Neutral and professional — works for most stores.",
    "Neutral",
    {
      primary: "#0f766e",
      secondary: "#475569",
      accent: "#ea580c",
      background: "#f1f5f9",
      foreground: "#0f172a",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#dce3eb",
      muted: "#64748b",
      success: "#15803d",
      warning: "#b45309",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#2dd4bf",
      secondary: "#94a3b8",
      accent: "#fb923c",
      background: "#0b1218",
      foreground: "#eef2f7",
      surface: "#121a22",
      card: "#18222c",
      border: "#2a3642",
      muted: "#94a3b8",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#0b1218",
  ),
  pack(
    "luxury-gold",
    "Luxury gold",
    "Warm elegance — jewelry, gifts, and premium goods.",
    "Luxury",
    {
      primary: "#92400e",
      secondary: "#44403c",
      accent: "#b45309",
      background: "#faf7f2",
      foreground: "#1c1917",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#e8e0d4",
      muted: "#78716c",
      success: "#3f6212",
      warning: "#a16207",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#fbbf24",
      secondary: "#a8a29e",
      accent: "#f59e0b",
      background: "#14110c",
      foreground: "#faf7f2",
      surface: "#1f1a14",
      card: "#292219",
      border: "#3f3426",
      muted: "#a8a29e",
      success: "#a3e635",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#14110c",
  ),
  pack(
    "berry",
    "Berry",
    "Bold and vibrant — fashion and seasonal collections.",
    "Bold",
    {
      primary: "#9f1239",
      secondary: "#4c1d3a",
      accent: "#e11d48",
      background: "#fff5f7",
      foreground: "#1f1218",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#f0d5dd",
      muted: "#7c5a66",
      success: "#15803d",
      warning: "#b45309",
      error: "#be123c",
    },
    "#ffffff",
    {
      primary: "#fb7185",
      secondary: "#c4a4b0",
      accent: "#f43f5e",
      background: "#160b10",
      foreground: "#fff5f7",
      surface: "#221018",
      card: "#2c1520",
      border: "#452433",
      muted: "#c4a4b0",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#fb7185",
    },
    "#160b10",
  ),
  pack(
    "terracotta",
    "Terracotta",
    "Earthy warmth — home, craft, and artisan brands.",
    "Warm",
    {
      primary: "#c2410c",
      secondary: "#57534e",
      accent: "#ea580c",
      background: "#faf6f3",
      foreground: "#1c1917",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#e8ddd4",
      muted: "#78716c",
      success: "#3f6212",
      warning: "#a16207",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#fdba74",
      secondary: "#a8a29e",
      accent: "#fb923c",
      background: "#17110e",
      foreground: "#faf6f3",
      surface: "#221814",
      card: "#2c1f19",
      border: "#433028",
      muted: "#a8a29e",
      success: "#a3e635",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#17110e",
  ),
  pack(
    "midnight",
    "Midnight",
    "Deep and modern — electronics and tech-forward stores.",
    "Dark",
    {
      primary: "#1e3a5f",
      secondary: "#334155",
      accent: "#38bdf8",
      background: "#f5f7fb",
      foreground: "#0f172a",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#d8e0ec",
      muted: "#64748b",
      success: "#15803d",
      warning: "#b45309",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#7dd3fc",
      secondary: "#94a3b8",
      accent: "#38bdf8",
      background: "#070b14",
      foreground: "#e8eef8",
      surface: "#0e1522",
      card: "#141c2c",
      border: "#243247",
      muted: "#94a3b8",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#070b14",
  ),
  pack(
    "lavender",
    "Lavender",
    "Soft purple calm — wellness, spa, and lifestyle.",
    "Soft",
    {
      primary: "#6d28d9",
      secondary: "#57534e",
      accent: "#a78bfa",
      background: "#faf8ff",
      foreground: "#1e1b2e",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#e4dff2",
      muted: "#6b6578",
      success: "#15803d",
      warning: "#b45309",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#c4b5fd",
      secondary: "#a8a29e",
      accent: "#a78bfa",
      background: "#120f1a",
      foreground: "#f5f2ff",
      surface: "#1b1626",
      card: "#241e32",
      border: "#3a314d",
      muted: "#b0a8c0",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#120f1a",
  ),
  pack(
    "coral",
    "Coral",
    "Energetic and friendly — lifestyle and gifts.",
    "Bold",
    {
      primary: "#e11d48",
      secondary: "#57534e",
      accent: "#fb7185",
      background: "#fff8f7",
      foreground: "#1c1917",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#f0d9d6",
      muted: "#78716c",
      success: "#15803d",
      warning: "#b45309",
      error: "#be123c",
    },
    "#ffffff",
    {
      primary: "#fb7185",
      secondary: "#a8a29e",
      accent: "#fda4af",
      background: "#180c0e",
      foreground: "#fff8f7",
      surface: "#241416",
      card: "#2e1a1d",
      border: "#4a2a30",
      muted: "#a8a29e",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#fb7185",
    },
    "#180c0e",
  ),
  pack(
    "emerald",
    "Emerald",
    "Confident green — outdoor, eco, and fresh produce.",
    "Nature",
    {
      primary: "#047857",
      secondary: "#334155",
      accent: "#10b981",
      background: "#f3faf7",
      foreground: "#0f172a",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#d5e8df",
      muted: "#64748b",
      success: "#15803d",
      warning: "#b45309",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#34d399",
      secondary: "#94a3b8",
      accent: "#6ee7b7",
      background: "#0a1411",
      foreground: "#e8f7f1",
      surface: "#12201b",
      card: "#182a23",
      border: "#2a4036",
      muted: "#94a3b8",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#0a1411",
  ),
  pack(
    "sand",
    "Sand",
    "Soft neutrals — apparel, home, and minimal catalogs.",
    "Neutral",
    {
      primary: "#78716c",
      secondary: "#57534e",
      accent: "#d97706",
      background: "#faf8f5",
      foreground: "#1c1917",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#e7e2db",
      muted: "#78716c",
      success: "#3f6212",
      warning: "#a16207",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#d6d3d1",
      secondary: "#a8a29e",
      accent: "#fbbf24",
      background: "#141210",
      foreground: "#faf8f5",
      surface: "#1e1b18",
      card: "#28241f",
      border: "#3d3730",
      muted: "#a8a29e",
      success: "#a3e635",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#141210",
  ),
  pack(
    "royal-blue",
    "Royal blue",
    "Strong and classic — electronics and professional brands.",
    "Modern",
    {
      primary: "#1d4ed8",
      secondary: "#334155",
      accent: "#f59e0b",
      background: "#f5f7fc",
      foreground: "#0f172a",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#d6deed",
      muted: "#64748b",
      success: "#15803d",
      warning: "#b45309",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#60a5fa",
      secondary: "#94a3b8",
      accent: "#fbbf24",
      background: "#0a1020",
      foreground: "#e8eef8",
      surface: "#121a2e",
      card: "#182338",
      border: "#2a3854",
      muted: "#94a3b8",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#0a1020",
  ),
  pack(
    "citrus",
    "Citrus",
    "Bright and energetic — groceries, juice, and summer shops.",
    "Warm",
    {
      primary: "#ca8a04",
      secondary: "#44403c",
      accent: "#65a30d",
      background: "#fffdf5",
      foreground: "#1c1917",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#ebe4d0",
      muted: "#78716c",
      success: "#3f6212",
      warning: "#a16207",
      error: "#b91c1c",
    },
    "#1c1917",
    {
      primary: "#facc15",
      secondary: "#a8a29e",
      accent: "#a3e635",
      background: "#15130c",
      foreground: "#fffdf5",
      surface: "#211e14",
      card: "#2b271a",
      border: "#423c28",
      muted: "#a8a29e",
      success: "#a3e635",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#15130c",
  ),
  pack(
    "olive",
    "Olive",
    "Quiet botanical green — markets, gardens, and natural goods.",
    "Nature",
    {
      primary: "#556b2f",
      secondary: "#4a5568",
      accent: "#c4a35a",
      background: "#f7f6f1",
      foreground: "#1a1c16",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#e2e0d6",
      muted: "#6b6e63",
      success: "#3f6212",
      warning: "#a16207",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#a3b18a",
      secondary: "#94a3b8",
      accent: "#e9c46a",
      background: "#12140f",
      foreground: "#f4f3ec",
      surface: "#1c2018",
      card: "#242a1f",
      border: "#363e30",
      muted: "#a8ad9c",
      success: "#a3e635",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#12140f",
  ),
  pack(
    "azure",
    "Azure",
    "Bright clear blue — travel, tech, and clean retail.",
    "Modern",
    {
      primary: "#0284c7",
      secondary: "#475569",
      accent: "#06b6d4",
      background: "#f0f9ff",
      foreground: "#0c1a24",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#d0e6f5",
      muted: "#5b7385",
      success: "#15803d",
      warning: "#b45309",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#38bdf8",
      secondary: "#94a3b8",
      accent: "#22d3ee",
      background: "#071018",
      foreground: "#e8f4fc",
      surface: "#0e1a24",
      card: "#142432",
      border: "#243849",
      muted: "#94a3b8",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#071018",
  ),
  pack(
    "plum",
    "Plum",
    "Deep wine tones — fashion, wine, and evening brands.",
    "Luxury",
    {
      primary: "#6b2142",
      secondary: "#4c3a45",
      accent: "#c084a8",
      background: "#fbf7f9",
      foreground: "#1f1218",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#eadde4",
      muted: "#7a6570",
      success: "#15803d",
      warning: "#b45309",
      error: "#9f1239",
    },
    "#ffffff",
    {
      primary: "#e9a8c7",
      secondary: "#b8a4ad",
      accent: "#f0abd0",
      background: "#140c11",
      foreground: "#fbf7f9",
      surface: "#1f141a",
      card: "#291c23",
      border: "#3f2c36",
      muted: "#b8a4ad",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#fb7185",
    },
    "#140c11",
  ),
  pack(
    "charcoal",
    "Charcoal",
    "Graphite neutrals — architecture and premium catalogs.",
    "Dark",
    {
      primary: "#36454f",
      secondary: "#5c6b73",
      accent: "#c0a16b",
      background: "#f4f5f6",
      foreground: "#121516",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#d9dee1",
      muted: "#667177",
      success: "#15803d",
      warning: "#b45309",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#cbd5e1",
      secondary: "#94a3b8",
      accent: "#e2c08d",
      background: "#0c0f11",
      foreground: "#f4f5f6",
      surface: "#15191c",
      card: "#1c2226",
      border: "#2c353b",
      muted: "#94a3b8",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#0c0f11",
  ),
  pack(
    "monochrome",
    "Monochrome",
    "Strict black and white — editorial and gallery stores.",
    "Neutral",
    {
      primary: "#171717",
      secondary: "#525252",
      accent: "#737373",
      background: "#fafafa",
      foreground: "#0a0a0a",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#e5e5e5",
      muted: "#737373",
      success: "#15803d",
      warning: "#a16207",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#fafafa",
      secondary: "#a3a3a3",
      accent: "#d4d4d4",
      background: "#0a0a0a",
      foreground: "#fafafa",
      surface: "#171717",
      card: "#1f1f1f",
      border: "#2e2e2e",
      muted: "#a3a3a3",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#0a0a0a",
  ),
  pack(
    "cream",
    "Cream",
    "Warm paper tones — bakeries, books, and soft retail.",
    "Soft",
    {
      primary: "#8b6914",
      secondary: "#6b5e4e",
      accent: "#c4a574",
      background: "#fbf8f1",
      foreground: "#1c1914",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#ebe4d6",
      muted: "#7a7164",
      success: "#3f6212",
      warning: "#a16207",
      error: "#b91c1c",
    },
    "#ffffff",
    {
      primary: "#e8d5a3",
      secondary: "#b0a593",
      accent: "#d4b896",
      background: "#15120e",
      foreground: "#fbf8f1",
      surface: "#201c16",
      card: "#2a241c",
      border: "#3f362a",
      muted: "#b0a593",
      success: "#a3e635",
      warning: "#fbbf24",
      error: "#f87171",
    },
    "#15120e",
  ),
  pack(
    "rose",
    "Rose",
    "Soft rose accents — beauty, florals, and gifts.",
    "Soft",
    {
      primary: "#be185d",
      secondary: "#6b5b63",
      accent: "#f472b6",
      background: "#fff7fa",
      foreground: "#1c1216",
      surface: "#ffffff",
      card: "#ffffff",
      border: "#f0d8e3",
      muted: "#7a6570",
      success: "#15803d",
      warning: "#b45309",
      error: "#be123c",
    },
    "#ffffff",
    {
      primary: "#f9a8d4",
      secondary: "#b8a4ad",
      accent: "#fda4af",
      background: "#160b11",
      foreground: "#fff7fa",
      surface: "#22141b",
      card: "#2c1a23",
      border: "#452833",
      muted: "#b8a4ad",
      success: "#4ade80",
      warning: "#fbbf24",
      error: "#fb7185",
    },
    "#160b11",
  ),

];

export const THEME_COLOR_PACK_CATEGORIES: ThemeColorPackCategory[] = [
  "Nature",
  "Warm",
  "Modern",
  "Luxury",
  "Soft",
  "Bold",
  "Neutral",
  "Dark",
];

export function packsByCategory(): Array<{
  category: ThemeColorPackCategory;
  packs: ThemeColorPack[];
}> {
  return THEME_COLOR_PACK_CATEGORIES.map((category) => ({
    category,
    packs: THEME_COLOR_PACKS.filter((packItem) => packItem.category === category),
  })).filter((group) => group.packs.length > 0);
}

export function findMatchingThemePackId(
  light: ColorTokens,
  dark: ColorTokens,
): string | null {
  for (const packItem of THEME_COLOR_PACKS) {
    if (
      packItem.light.primary === light.primary &&
      packItem.light.background === light.background &&
      packItem.dark.primary === dark.primary &&
      packItem.dark.background === dark.background
    ) {
      return packItem.id;
    }
  }
  return null;
}
